# Generated by Django 3.2.7 on 2021-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
