# Generated by Django 3.2.7 on 2021-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_user_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_postcode',
            new_name='user_postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_door_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_town_or_city',
        ),
    ]
