# Generated by Django 3.2.7 on 2021-10-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211028_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_contact_number',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_postal_code',
            new_name='postal_code',
        ),
    ]
