# Generated by Django 3.2.7 on 2021-10-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20211028_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact_number',
            new_name='user_contact_number',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='user_full_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='postal_code',
            new_name='user_postal_code',
        ),
    ]
