# Generated by Django 3.2.7 on 2021-10-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211028_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_address',
            new_name='user_street_address',
        ),
    ]
