# Generated by Django 3.2.7 on 2021-10-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_user_address_userprofile_user_street_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_street_address',
            new_name='user_address',
        ),
    ]
