# Generated by Django 3.2.7 on 2022-01-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_number',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='message',
            name='full_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='', max_length=300),
        ),
    ]
