# Generated by Django 3.2.7 on 2021-10-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='door_no',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=40),
        ),
    ]
