# Generated by Django 3.2.7 on 2021-10-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20211017_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
