# Generated by Django 3.2.7 on 2022-02-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
