# Generated by Django 3.2.7 on 2022-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card payment', 'card payment'), ('cash on delivery', 'cash on delivery')], default='card payment', max_length=20),
        ),
    ]
