# Generated by Django 3.2.7 on 2022-02-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_promise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promise',
        ),
    ]
