# Generated by Django 3.2.7 on 2022-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Card', 'Card')], default='Cash on Delivery', max_length=30),
        ),
    ]
