# Generated by Django 3.2.7 on 2021-11-07 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_user_street_address_userprofile_user_address'),
        ('reviews', '0002_review_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewing_user',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
    ]
