# Generated by Django 3.2.7 on 2022-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='heading',
            field=models.TextField(blank=True, max_length=170, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True, max_length=170, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=270, null=True),
        ),
    ]
