# Generated by Django 3.2.7 on 2022-01-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20220104_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allergen',
            field=models.TextField(blank=True, max_length=270, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='heading',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
    ]
