# Generated by Django 3.2.7 on 2022-01-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20220104_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natasha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(choices=[('Fish', 'Fish'), ('Egg', 'Egg'), ('Milk', 'Milk')], max_length=300)),
            ],
        ),
    ]
