# Generated by Django 3.2.7 on 2022-01-04 14:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_natasha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Natasha',
        ),
        migrations.AlterField(
            model_name='item',
            name='allergen',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fish', 'Fish'), ('Egg', 'Egg'), ('Milk', 'Milk')], max_length=13, null=True),
        ),
    ]
