# Generated by Django 3.2.7 on 2022-01-04 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_item_allergen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
    ]
