# Generated by Django 3.2.7 on 2022-01-05 18:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='allergen',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Celery', 'Celery'), ('Cereals containing gluten', 'Cereals containing gluten'), ('Crustaceans', 'Crustaceans'), ('Egg', 'Egg'), ('Fish', 'Fish'), ('Lupin', 'Lupin'), ('Milk', 'Milk'), ('Molluscs', 'Molluscs'), ('Mustard', 'Mustard'), ('Tree nuts/Nuts', 'Tree nuts/Nuts'), ('Peanuts', 'Peanuts'), ('Sesame Seeds', 'Sesame Seeds'), ('Soya', 'Soya'), ('Sulphur Dioxide/Sulphite', 'Sulphur Dioxide/Sulphite'), ('None', 'None')], max_length=152, null=True),
        ),
    ]
