# Generated by Django 3.2.7 on 2022-01-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredient',
            field=models.TextField(blank=True, max_length=370, null=True),
        ),
    ]
