# Generated by Django 3.2.7 on 2022-01-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_item_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=370, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='heading',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ingredient',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
