# Generated by Django 3.2.7 on 2022-01-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_auto_20220119_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='note',
            new_name='note1',
        ),
        migrations.AddField(
            model_name='item',
            name='note2',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='note3',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
