# Generated by Django 3.2.7 on 2022-01-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_auto_20220119_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
    ]
