# Generated by Django 3.2.7 on 2022-01-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vegan',
            field=models.BooleanField(null=True),
        ),
    ]
