# Generated by Django 3.2.7 on 2022-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_alter_item_note3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='note3',
            field=models.TextField(blank=True, default='Please note that we handle all allergens                            in our kitchen therefore we                            cannot guarantee that our                            dishes are 100% allergen-free.                            If you have any allergy and                            intolerance, please inform us                            before you place your order so                            we can provide you with                            information to help you make                            a safe and informed choice.', max_length=780, null=True),
        ),
    ]
