# Generated by Django 3.2.7 on 2022-02-11 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_alter_item_note3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['date', 'name']},
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
