# Generated by Django 3.2.7 on 2022-02-11 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_item_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='added_by',
        ),
    ]
