# Generated by Django 3.2.7 on 2022-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_remove_item_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='note1',
            field=models.TextField(blank=True, max_length=11000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='note2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='note3',
            field=models.TextField(blank=True, default='Please note that we handle all allergens                            in our kitchen therefore we                            cannot guarantee that our                            dishes are 100% allergen-free.                            If you have any allergy and                            intolerance, please inform us                            before you place your order so                            we can provide you with                            information to help you make                            a safe and informed choice.', max_length=1180, null=True),
        ),
    ]
