# Generated by Django 3.2.7 on 2022-03-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_auto_20220216_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ingredient',
            new_name='materials',
        ),
        migrations.RemoveField(
            model_name='item',
            name='allergen',
        ),
        migrations.RemoveField(
            model_name='item',
            name='chillies',
        ),
        migrations.RemoveField(
            model_name='item',
            name='note3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='vegan',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
